In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
train = pd.read_csv('TRAIN.csv')
test = pd.read_csv('TEST.csv')

In [3]:
train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957    Male   50                1           41                   0   
1  239788  Female   48                1           28                   0   
2  348272  Female   34                1           41                   0   
3   73940  Female   43                1           28                   0   
4  292871    Male   29                1           28                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes           35915                   124      240   
1    1-2 Year            Yes           26873                   124      274   
2    1-2 Year            Yes            2630                   156      138   
3    1-2 Year            Yes           46877                   124      223   
4    < 1 Year             No           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [4]:
train.shape

(304887, 12)

In [5]:
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304887 entries, 0 to 304886
Data columns (total 12 columns):
 #   Column                Non-Null Count   Dtype 
---  ------                --------------   ----- 
 0   id                    304887 non-null  int64 
 1   Gender                304887 non-null  object
 2   Age                   304887 non-null  int64 
 3   Driving_License       304887 non-null  int64 
 4   Region_Code           304887 non-null  int64 
 5   Previously_Insured    304887 non-null  int64 
 6   Vehicle_Age           304887 non-null  object
 7   Vehicle_Damage        304887 non-null  object
 8   Annual_Premium        304887 non-null  int64 
 9   Policy_Sales_Channel  304887 non-null  int64 
 10  Vintage               304887 non-null  int64 
 11  Response              304887 non-null  int64 
dtypes: int64(9), object(3)
memory usage: 27.9+ MB


In [6]:
train.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
dtype: int64

In [7]:
train.Response.value_counts()

0    267582
1     37305
Name: Response, dtype: int64

In [8]:
test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  291378    Male   31                1           18                   0   
1  154746  Female   24                1           15                   1   
2  218512  Female   25                1           14                   1   
3  173930    Male   49                1           28                   0   
4  241471    Male   55                1           45                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    1-2 Year            Yes            2630                   156      152  
1    < 1 Year             No           28105                   152      267  
2    < 1 Year             No           29302                   152      139  
3    1-2 Year            Yes           28357                    26       12  
4    1-2 Year            Yes           33288                    26       44

In [9]:
train['Vehicle_Age'].value_counts()

1-2 Year     160244
< 1 Year     131823
> 2 Years     12820
Name: Vehicle_Age, dtype: int64

In [10]:
train['Gender'].value_counts()

Male      164823
Female    140064
Name: Gender, dtype: int64

In [11]:
train['Gender'].replace(['Male','Female'],[1,0],inplace = True)

In [12]:
train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957       1   50                1           41                   0   
1  239788       0   48                1           28                   0   
2  348272       0   34                1           41                   0   
3   73940       0   43                1           28                   0   
4  292871       1   29                1           28                   1   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes           35915                   124      240   
1    1-2 Year            Yes           26873                   124      274   
2    1-2 Year            Yes            2630                   156      138   
3    1-2 Year            Yes           46877                   124      223   
4    < 1 Year             No           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [13]:
train['Vehicle_Damage'].value_counts()

Yes    153897
No     150990
Name: Vehicle_Damage, dtype: int64

In [14]:
train['Vehicle_Damage'].replace(['Yes','No'],[1,0],inplace = True)

In [15]:
train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957       1   50                1           41                   0   
1  239788       0   48                1           28                   0   
2  348272       0   34                1           41                   0   
3   73940       0   43                1           28                   0   
4  292871       1   29                1           28                   1   

  Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year               1           35915                   124      240   
1    1-2 Year               1           26873                   124      274   
2    1-2 Year               1            2630                   156      138   
3    1-2 Year               1           46877                   124      223   
4    < 1 Year               0           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [16]:
train['Vehicle_Age'].replace(['1-2 Year','< 1 Year','> 2 Years'],[1,0,2],inplace = True)

In [17]:
train.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  350957       1   50                1           41                   0   
1  239788       0   48                1           28                   0   
2  348272       0   34                1           41                   0   
3   73940       0   43                1           28                   0   
4  292871       1   29                1           28                   1   

   Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0            1               1           35915                   124      240   
1            1               1           26873                   124      274   
2            1               1            2630                   156      138   
3            1               1           46877                   124      223   
4            0               0           38009                   152      106   

   Response  
0         0  
1         0  
2         1  
3         0  
4         0

In [18]:
X = train.drop(['id','Response', 'Region_Code','Annual_Premium'],axis=1)
y = pd.DataFrame(train['Response'])

In [19]:
X

Gender  Age  Driving_License  Previously_Insured  Vehicle_Age  \
0            1   50                1                   0            1   
1            0   48                1                   0            1   
2            0   34                1                   0            1   
3            0   43                1                   0            1   
4            1   29                1                   1            0   
...        ...  ...              ...                 ...          ...   
304882       1   69                1                   0            2   
304883       1   24                1                   1            0   
304884       0   46                1                   0            1   
304885       0   77                1                   1            1   
304886       0   25                1                   1            0   

        Vehicle_Damage  Policy_Sales_Channel  Vintage  
0                    1                   124      240  
1                    1                   124      274  
2                    1                   156      138  
3                    1                   124      223  
4                    0                   152      106  
...                ...                   ...      ...  
304882               1                    26      270  
304883               0                   152       68  
304884               1                   154      155  
304885               0                   122       60  
304886               0                   152      120  

[304887 rows x 8 columns]

In [20]:
y

Response
0              0
1              0
2              1
3              0
4              0
...          ...
304882         0
304883         0
304884         0
304885         0
304886         0

[304887 rows x 1 columns]

In [21]:
from sklearn.preprocessing import StandardScaler
ss = StandardScaler()
scaled = ss.fit_transform(X)

#from sklearn.preprocessing import MinMaxScaler
#ss = MinMaxScaler(feature_range=(5, 10))
#scaled = ss.fit_transform(X)

#from sklearn.preprocessing import MaxAbsScaler
#ss = MaxAbsScaler()
#scaled = ss.fit_transform(X)

#from sklearn.preprocessing import RobustScaler
#ss = RobustScaler()
#scaled = ss.fit_transform(X)

In [22]:
scaled

array([[ 0.92183747,  0.71952278,  0.04615089, ...,  0.99051034,
         0.22094799,  1.02381674],
       [-1.08478993,  0.59066213,  0.04615089, ...,  0.99051034,
         0.22094799,  1.42996573],
       [-1.08478993, -0.31136241,  0.04615089, ...,  0.99051034,
         0.81122212, -0.19463025],
       ...,
       [-1.08478993,  0.46180148,  0.04615089, ...,  0.99051034,
         0.77432999,  0.00844425],
       [-1.08478993,  2.45914154,  0.04615089, ..., -1.00958057,
         0.18405585, -1.12638382],
       [-1.08478993, -0.89123533,  0.04615089, ..., -1.00958057,
         0.73743785, -0.4096503 ]])

In [23]:
from sklearn.model_selection import train_test_split

In [24]:
X_train, X_test, y_train, y_test = train_test_split(scaled, y, test_size=0.25)

In [25]:
X_train.shape, X_test.shape

((228665, 8), (76222, 8))

# Logistic Regression

In [26]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(random_state = 42)
lr.fit(X_train, y_train.values.ravel())

LogisticRegression(random_state=42)

In [27]:
y_pred = lr.predict(X_test)

In [28]:
y_pred

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [29]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [30]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     66935
           1       0.39      0.00      0.00      9287

    accuracy                           0.88     76222
   macro avg       0.63      0.50      0.47     76222
weighted avg       0.82      0.88      0.82     76222



In [31]:
print(confusion_matrix(y_pred, y_test))

[[66899  9264]
 [   36    23]]


In [32]:
from sklearn import metrics 
print("Logistic Regression accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)

Logistic Regression accuracy(in %): 87.7987982472252


# Test

In [63]:
test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  291378    Male   31                1           18                   0   
1  154746  Female   24                1           15                   1   
2  218512  Female   25                1           14                   1   
3  173930    Male   49                1           28                   0   
4  241471    Male   55                1           45                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0    1-2 Year            Yes            2630                   156      152  
1    < 1 Year             No           28105                   152      267  
2    < 1 Year             No           29302                   152      139  
3    1-2 Year            Yes           28357                    26       12  
4    1-2 Year            Yes           33288                    26       44

In [64]:
test['Gender'].replace(['Male','Female'],[1,0],inplace = True)

In [65]:
test['Vehicle_Damage'].replace(['Yes','No'],[1,0],inplace = True)

In [66]:
test['Vehicle_Age'].replace(['1-2 Year','< 1 Year','> 2 Years'],[1,0,2],inplace = True)

In [67]:
test.head()

id  Gender  Age  Driving_License  Region_Code  Previously_Insured  \
0  291378       1   31                1           18                   0   
1  154746       0   24                1           15                   1   
2  218512       0   25                1           14                   1   
3  173930       1   49                1           28                   0   
4  241471       1   55                1           45                   0   

   Vehicle_Age  Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  
0            1               1            2630                   156      152  
1            0               0           28105                   152      267  
2            0               0           29302                   152      139  
3            1               1           28357                    26       12  
4            1               1           33288                    26       44

In [68]:
test.drop(["id",'Region_Code','Annual_Premium'],axis=1, inplace=True)

In [69]:
test.head()

Gender  Age  Driving_License  Previously_Insured  Vehicle_Age  \
0       1   31                1                   0            1   
1       0   24                1                   1            0   
2       0   25                1                   1            0   
3       1   49                1                   0            1   
4       1   55                1                   0            1   

   Vehicle_Damage  Policy_Sales_Channel  Vintage  
0               1                   156      152  
1               0                   152      267  
2               0                   152      139  
3               1                    26       12  
4               1                    26       44

In [70]:
scaledtest = ss.fit_transform(test)

In [71]:
scaledtest

array([[ 0.92037471, -0.5029147 ,  0.04643543, ...,  0.98942902,
         0.81069509, -0.03071224],
       [-1.08651399, -0.95524934,  0.04643543, ..., -1.01068392,
         0.73685509,  1.34648509],
       [-1.08651399, -0.89063011,  0.04643543, ..., -1.01068392,
         0.73685509, -0.18639541],
       ...,
       [ 0.92037471,  0.78947   ,  0.04643543, ..., -1.01068392,
         0.21997509, -0.25824918],
       [ 0.92037471, -1.14910704,  0.04643543, ..., -1.01068392,
         0.88453509, -0.91690877],
       [-1.08651399,  0.27251612,  0.04643543, ...,  0.98942902,
         0.73685509,  1.46624137]])

In [72]:
pred1=lr.predict(scaledtest)

In [73]:
pred1

In [74]:
IDs = pd.read_csv("TEST.csv")[["id"]].values

In [75]:
df_for_submission = {'id': IDs.ravel(), 'Response': pred1}
df_submission_predictions = pd.DataFrame(df_for_submission).set_index(['id'])
df_submission_predictions.head(10)

In [76]:
df_submission_predictions.to_csv('Mysubmission44.csv')